<?php

namespace Objects;

class Constants {

    public const MAIL_ENCRYPTIONS = [
        'tls' => 'TLS',
        'ssl' => 'SSL'
    ];

    public const LANGUAGES = [
        'ba' => 'Bosnian',
        'de' => 'Deutsch',
        'en' => 'English',
        'fr' => 'Français',
        'cs' => "Czech"
    ];

    public const PRIORITIES = [
        "low",
        "medium",
        "high"
    ];

    public const PAYPAL_MODES = [
        'sandbox'    => [
            'backend'  => 'sandbox',
            'frontend' => 'sandbox'
        ],
        'production' => [
            'backend'  => 'live',
            'frontend' => 'production'
        ]
    ];

    public const INVOICE_SYSTEMS = [
        'none'      => '-',
        'billomat'  => "Billomat",
        'lexoffice' => "Lexoffice",
        'sevdesk'   => "SevDesk"
    ];

    public static function validatePasswordLength($password) {
        return (strlen($password) > 5);
    }

    public static function validateKey($key) {
        $key_parts = explode(' ', $key, 3);

        if (count($key_parts) < 2) {
            return false;
        }

        if (count($key_parts) > 3) {
            return false;
        }

        $algorithm = $key_parts[0];
        $key       = $key_parts[1];

        // if (!in_array($algorithm, [
        //     "rsa-sha2-256",
        //     "rsa-sha2-512",
        //     "ssh-rsa",
        //     "ecdsa-sha2-nistp256",
        //     "ecdsa-sha2-nistp384",
        //     "ecdsa-sha2-nistp521",
        //     "ssh-ed25519",
        //     "x509v3-rsa2048-sha256",
        //     "x509v3-ssh-rsa",
        //     "x509v3-sign-rsa",
        //     "x509v3-ecdsa-sha2-nistp256",
        //     "x509v3-ecdsa-sha2-nistp384",
        //     "x509v3-ecdsa-sha2-nistp521"
        // ])) {
        //     return false;
        // }

        $key_base64_decoded = base64_decode($key, true);

        if ($key_base64_decoded == false) {
            return false;
        }

        $check = base64_decode(substr($key, 0, 16));
        $check = preg_replace("/[^\w\-]/", "", $check);

        return true;
    }

    public static function validateHostname($hostname) {
        return (preg_match("/^([a-z\d](-*[a-z\d])*)(\.([a-z\d](-*[a-z\d])*))*$/i", $hostname) //valid chars check
            && preg_match("/^.{1,253}$/", $hostname) //overall length check
            && preg_match("/^[^\.]{1,63}(\.[^\.]{1,63})*$/", $hostname)); //length of each label
    }

    const COUNTRYS = [
        "4"   => "Afghanistan",
        "248" => "Åland Islands",
        "8"   => "Albania",
        "12"  => "Algeria",
        "16"  => "American Samoa",
        "20"  => "Andorra",
        "24"  => "Angola",
        "660" => "Anguilla",
        "10"  => "Antarctica",
        "28"  => "Antigua and Barbuda",
        "32"  => "Argentina",
        "51"  => "Armenia",
        "533" => "Aruba",
        "36"  => "Australia",
        "40"  => "Austria",
        "31"  => "Azerbaijan",
        "44"  => "Bahamas",
        "48"  => "Bahrain",
        "50"  => "Bangladesh",
        "52"  => "Barbados",
        "112" => "Belarus",
        "56"  => "Belgium",
        "84"  => "Belize",
        "204" => "Benin",
        "60"  => "Bermuda",
        "64"  => "Bhutan",
        "68"  => "Bolivia, Plurinational State of",
        "535" => "Bonaire, Sint Eustatius and Saba",
        "70"  => "Bosnia and Herzegovina",
        "72"  => "Botswana",
        "74"  => "Bouvet Island",
        "76"  => "Brazil",
        "86"  => "British Indian Ocean Territory",
        "96"  => "Brunei Darussalam",
        "100" => "Bulgaria",
        "854" => "Burkina Faso",
        "108" => "Burundi",
        "116" => "Cambodia",
        "120" => "Cameroon",
        "124" => "Canada",
        "132" => "Cape Verde",
        "136" => "Cayman Islands",
        "140" => "Central African Republic",
        "148" => "Chad",
        "152" => "Chile",
        "156" => "China",
        "162" => "Christmas Island",
        "166" => "Cocos (Keeling) Islands",
        "170" => "Colombia",
        "174" => "Comoros",
        "178" => "Congo",
        "180" => "Congo, the Democratic Republic of the",
        "184" => "Cook Islands",
        "188" => "Costa Rica",
        "384" => "Côte d'Ivoire",
        "191" => "Croatia",
        "192" => "Cuba",
        "531" => "Curaçao",
        "196" => "Cyprus",
        "203" => "Czech Republic",
        "208" => "Denmark",
        "262" => "Djibouti",
        "212" => "Dominica",
        "214" => "Dominican Republic",
        "218" => "Ecuador",
        "818" => "Egypt",
        "222" => "El Salvador",
        "226" => "Equatorial Guinea",
        "232" => "Eritrea",
        "233" => "Estonia",
        "231" => "Ethiopia",
        "238" => "Falkland Islands (Malvinas)",
        "234" => "Faroe Islands",
        "242" => "Fiji",
        "246" => "Finland",
        "250" => "France",
        "254" => "French Guiana",
        "258" => "French Polynesia",
        "260" => "French Southern Territories",
        "266" => "Gabon",
        "270" => "Gambia",
        "268" => "Georgia",
        "276" => "Germany",
        "288" => "Ghana",
        "292" => "Gibraltar",
        "300" => "Greece",
        "304" => "Greenland",
        "308" => "Grenada",
        "312" => "Guadeloupe",
        "316" => "Guam",
        "320" => "Guatemala",
        "831" => "Guernsey",
        "324" => "Guinea",
        "624" => "Guinea-Bissau",
        "328" => "Guyana",
        "332" => "Haiti",
        "334" => "Heard Island and McDonald Islands",
        "336" => "Holy See (Vatican City State)",
        "340" => "Honduras",
        "344" => "Hong Kong",
        "348" => "Hungary",
        "352" => "Iceland",
        "356" => "India",
        "360" => "Indonesia",
        "364" => "Iran, Islamic Republic of",
        "368" => "Iraq",
        "372" => "Ireland",
        "833" => "Isle of Man",
        "376" => "Israel",
        "380" => "Italy",
        "388" => "Jamaica",
        "392" => "Japan",
        "832" => "Jersey",
        "400" => "Jordan",
        "398" => "Kazakhstan",
        "404" => "Kenya",
        "296" => "Kiribati",
        "408" => "Korea, Democratic People's Republic of",
        "410" => "Korea, Republic of",
        "414" => "Kuwait",
        "417" => "Kyrgyzstan",
        "418" => "Lao People's Democratic Republic",
        "428" => "Latvia",
        "422" => "Lebanon",
        "426" => "Lesotho",
        "430" => "Liberia",
        "434" => "Libya",
        "438" => "Liechtenstein",
        "440" => "Lithuania",
        "442" => "Luxembourg",
        "446" => "Macao",
        "807" => "Macedonia, the former Yugoslav Republic of",
        "450" => "Madagascar",
        "454" => "Malawi",
        "458" => "Malaysia",
        "462" => "Maldives",
        "466" => "Mali",
        "470" => "Malta",
        "584" => "Marshall Islands",
        "474" => "Martinique",
        "478" => "Mauritania",
        "480" => "Mauritius",
        "175" => "Mayotte",
        "484" => "Mexico",
        "583" => "Micronesia, Federated States of",
        "498" => "Moldova, Republic of",
        "492" => "Monaco",
        "496" => "Mongolia",
        "499" => "Montenegro",
        "500" => "Montserrat",
        "504" => "Morocco",
        "508" => "Mozambique",
        "104" => "Myanmar",
        "516" => "Namibia",
        "520" => "Nauru",
        "524" => "Nepal",
        "528" => "Netherlands",
        "540" => "New Caledonia",
        "554" => "New Zealand",
        "558" => "Nicaragua",
        "562" => "Niger",
        "566" => "Nigeria",
        "570" => "Niue",
        "574" => "Norfolk Island",
        "580" => "Northern Mariana Islands",
        "578" => "Norway",
        "512" => "Oman",
        "586" => "Pakistan",
        "585" => "Palau",
        "275" => "Palestinian Territory, Occupied",
        "591" => "Panama",
        "598" => "Papua New Guinea",
        "600" => "Paraguay",
        "604" => "Peru",
        "608" => "Philippines",
        "612" => "Pitcairn",
        "616" => "Poland",
        "620" => "Portugal",
        "630" => "Puerto Rico",
        "634" => "Qatar",
        "638" => "Réunion",
        "642" => "Romania",
        "643" => "Russian Federation",
        "646" => "Rwanda",
        "652" => "Saint Barthélemy",
        "654" => "Saint Helena, Ascension and Tristan da Cunha",
        "659" => "Saint Kitts and Nevis",
        "662" => "Saint Lucia",
        "663" => "Saint Martin (French part)",
        "666" => "Saint Pierre and Miquelon",
        "670" => "Saint Vincent and the Grenadines",
        "882" => "Samoa",
        "674" => "San Marino",
        "678" => "Sao Tome and Principe",
        "682" => "Saudi Arabia",
        "686" => "Senegal",
        "688" => "Serbia",
        "690" => "Seychelles",
        "694" => "Sierra Leone",
        "702" => "Singapore",
        "534" => "Sint Maarten (Dutch part)",
        "703" => "Slovakia",
        "705" => "Slovenia",
        "90"  => "Solomon Islands",
        "706" => "Somalia",
        "710" => "South Africa",
        "239" => "South Georgia and the South Sandwich Islands",
        "728" => "South Sudan",
        "724" => "Spain",
        "144" => "Sri Lanka",
        "729" => "Sudan",
        "740" => "Suriname",
        "744" => "Svalbard and Jan Mayen",
        "748" => "Swaziland",
        "752" => "Sweden",
        "756" => "Switzerland",
        "760" => "Syrian Arab Republic",
        "158" => "Taiwan, Province of China",
        "762" => "Tajikistan",
        "834" => "Tanzania, United Republic of",
        "764" => "Thailand",
        "626" => "Timor-Leste",
        "768" => "Togo",
        "772" => "Tokelau",
        "776" => "Tonga",
        "780" => "Trinidad and Tobago",
        "788" => "Tunisia",
        "792" => "Turkey",
        "795" => "Turkmenistan",
        "796" => "Turks and Caicos Islands",
        "798" => "Tuvalu",
        "800" => "Uganda",
        "804" => "Ukraine",
        "784" => "United Arab Emirates",
        "826" => "United Kingdom",
        "840" => "United States",
        "581" => "United States Minor Outlying Islands",
        "858" => "Uruguay",
        "860" => "Uzbekistan",
        "548" => "Vanuatu",
        "862" => "Venezuela, Bolivarian Republic of",
        "704" => "Viet Nam",
        "92"  => "Virgin Islands, British",
        "850" => "Virgin Islands, U.S.",
        "876" => "Wallis and Futuna",
        "732" => "Western Sahara",
        "887" => "Yemen",
        "894" => "Zambia",
        "716" => "Zimbabwe"
    ];

    const COUNTRY_NUM_TO_ALPHA = [
        "004" => "AF",
        "008" => "AL",
        "012" => "DZ",
        "016" => "AS",
        "020" => "AD",
        "024" => "AO",
        "660" => "AI",
        "010" => "AQ",
        "028" => "AG",
        "032" => "AR",
        "051" => "AM",
        "533" => "AW",
        "036" => "AU",
        "040" => "AT",
        "031" => "AZ",
        "044" => "BS",
        "048" => "BH",
        "050" => "BD",
        "052" => "BB",
        "112" => "BY",
        "056" => "BE",
        "084" => "BZ",
        "204" => "BJ",
        "060" => "BM",
        "064" => "BT",
        "068" => "BO",
        "535" => "BQ",
        "070" => "BA",
        "072" => "BW",
        "074" => "BV",
        "076" => "BR",
        "086" => "IO",
        "096" => "BN",
        "100" => "BG",
        "854" => "BF",
        "108" => "BI",
        "132" => "CV",
        "116" => "KH",
        "120" => "CM",
        "124" => "CA",
        "136" => "KY",
        "140" => "CF",
        "148" => "TD",
        "152" => "CL",
        "156" => "CN",
        "162" => "CX",
        "166" => "CC",
        "170" => "CO",
        "174" => "KM",
        "180" => "CD",
        "178" => "CG",
        "184" => "CK",
        "188" => "CR",
        "191" => "HR",
        "192" => "CU",
        "531" => "CW",
        "196" => "CY",
        "203" => "CZ",
        "384" => "CI",
        "208" => "DK",
        "262" => "DJ",
        "212" => "DM",
        "214" => "DO",
        "218" => "EC",
        "818" => "EG",
        "222" => "SV",
        "226" => "GQ",
        "232" => "ER",
        "233" => "EE",
        "748" => "SZ",
        "231" => "ET",
        "238" => "FK",
        "234" => "FO",
        "242" => "FJ",
        "246" => "FI",
        "250" => "FR",
        "254" => "GF",
        "258" => "PF",
        "260" => "TF",
        "266" => "GA",
        "270" => "GM",
        "268" => "GE",
        "276" => "DE",
        "288" => "GH",
        "292" => "GI",
        "300" => "GR",
        "304" => "GL",
        "308" => "GD",
        "312" => "GP",
        "316" => "GU",
        "320" => "GT",
        "831" => "GG",
        "324" => "GN",
        "624" => "GW",
        "328" => "GY",
        "332" => "HT",
        "334" => "HM",
        "336" => "VA",
        "340" => "HN",
        "344" => "HK",
        "348" => "HU",
        "352" => "IS",
        "356" => "IN",
        "360" => "ID",
        "364" => "IR",
        "368" => "IQ",
        "372" => "IE",
        "833" => "IM",
        "376" => "IL",
        "380" => "IT",
        "388" => "JM",
        "392" => "JP",
        "832" => "JE",
        "400" => "JO",
        "398" => "KZ",
        "404" => "KE",
        "296" => "KI",
        "408" => "KP",
        "410" => "KR",
        "414" => "KW",
        "417" => "KG",
        "418" => "LA",
        "428" => "LV",
        "422" => "LB",
        "426" => "LS",
        "430" => "LR",
        "434" => "LY",
        "438" => "LI",
        "440" => "LT",
        "442" => "LU",
        "446" => "MO",
        "450" => "MG",
        "454" => "MW",
        "458" => "MY",
        "462" => "MV",
        "466" => "ML",
        "470" => "MT",
        "584" => "MH",
        "474" => "MQ",
        "478" => "MR",
        "480" => "MU",
        "175" => "YT",
        "484" => "MX",
        "583" => "FM",
        "498" => "MD",
        "492" => "MC",
        "496" => "MN",
        "499" => "ME",
        "500" => "MS",
        "504" => "MA",
        "508" => "MZ",
        "104" => "MM",
        "516" => "NA",
        "520" => "NR",
        "524" => "NP",
        "528" => "NL",
        "540" => "NC",
        "554" => "NZ",
        "558" => "NI",
        "562" => "NE",
        "566" => "NG",
        "570" => "NU",
        "574" => "NF",
        "580" => "MP",
        "578" => "NO",
        "512" => "OM",
        "586" => "PK",
        "585" => "PW",
        "275" => "PS",
        "591" => "PA",
        "598" => "PG",
        "600" => "PY",
        "604" => "PE",
        "608" => "PH",
        "612" => "PN",
        "616" => "PL",
        "620" => "PT",
        "630" => "PR",
        "634" => "QA",
        "807" => "MK",
        "642" => "RO",
        "643" => "RU",
        "646" => "RW",
        "638" => "RE",
        "652" => "BL",
        "654" => "SH",
        "659" => "KN",
        "662" => "LC",
        "663" => "MF",
        "666" => "PM",
        "670" => "VC",
        "882" => "WS",
        "674" => "SM",
        "678" => "ST",
        "682" => "SA",
        "686" => "SN",
        "688" => "RS",
        "690" => "SC",
        "694" => "SL",
        "702" => "SG",
        "534" => "SX",
        "703" => "SK",
        "705" => "SI",
        "090" => "SB",
        "706" => "SO",
        "710" => "ZA",
        "239" => "GS",
        "728" => "SS",
        "724" => "ES",
        "144" => "LK",
        "729" => "SD",
        "740" => "SR",
        "744" => "SJ",
        "752" => "SE",
        "756" => "CH",
        "760" => "SY",
        "158" => "TW",
        "762" => "TJ",
        "834" => "TZ",
        "764" => "TH",
        "626" => "TL",
        "768" => "TG",
        "772" => "TK",
        "776" => "TO",
        "780" => "TT",
        "788" => "TN",
        "792" => "TR",
        "795" => "TM",
        "796" => "TC",
        "798" => "TV",
        "800" => "UG",
        "804" => "UA",
        "784" => "AE",
        "826" => "GB",
        "581" => "UM",
        "840" => "US",
        "858" => "UY",
        "860" => "UZ",
        "548" => "VU",
        "862" => "VE",
        "704" => "VN",
        "092" => "VG",
        "850" => "VI",
        "876" => "WF",
        "732" => "EH",
        "887" => "YE",
        "894" => "ZM",
        "716" => "ZW",
        "248" => "AX"
    ];

    const EU_COUNTRYS = [
        'BE',
        'BG',
        'DK',
        'DE',
        'EE',
        'FI',
        'FR',
        'GR',
        'IE',
        'IT',
        'HR',
        'LV',
        'LT',
        'LU',
        'MT',
        'NL',
        'AT',
        'PL',
        'PT',
        'RO',
        'SE',
        'SK',
        'SI',
        'ES',
        'CZ',
        'HU',
        'CY'
    ];
}
